services:
  cargo:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .docker/Dockerfile
    entrypoint:
      - "cargo"
    working_dir: /var/app
    volumes:
      - "./:/var/app"
