name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: varese-ordinanze-push-notifier
        path: target/x86_64-unknown-linux-gnu/release/varese-ordinanze-push-notifier
